### ISSUE TITLE
environment/2way-ssl errors in broker2

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1003]
```
[2021-05-26 07:37:11,510] INFO [Producer clientId=ConfluentBalancerSampleStoreProducer] Failed authentication with /0.0.0.0 (errorMessage=SSL handshake failed caused by No subject alternative names matching IP address 0.0.0.0 found) (org.apache.kafka.common.network.Selector)
[2021-05-26 07:37:11,510] ERROR [Producer clientId=ConfluentBalancerSampleStoreProducer] Connection to node -1 (/0.0.0.0:9093) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-05-26 07:37:11,510] WARN [Producer clientId=ConfluentBalancerSampleStoreProducer] Bootstrap broker 0.0.0.0:9093 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-05-26 07:37:11,510] INFO [SocketServer brokerId=2] Failed authentication with /192.168.16.3 (errorMessage=SSL handshake failed caused by Unexpected content: 20) (org.apache.kafka.common.network.Selector)
```

**Comment by vdesabou** [comment]
still seeing it in ssl_kerberos

**Comment by vdesabou** [comment]
```
[2021-06-22 15:09:06,720] INFO DataBalancer: Instantiating DataBalanceEngine (io.confluent.databalancer.ConfluentDataBalanceEngine)
[2021-06-22 15:09:06,727] INFO DataBalancer: Listener endpoint is Endpoint(listenerName='SASL_SSL', securityProtocol=SASL_SSL, host='0.0.0.0', port=9092) (io.confluent.databalancer.startup.CruiseControlStartable)
[2021-06-22 15:09:06,731] INFO DataBalancer: BOOTSTRAP_SERVERS determined to be 0.0.0.0:9092 (io.confluent.databalancer.startup.CruiseControlStartable)
```


```
[2021-06-22 15:09:07,858] ERROR Error while checking topic _confluent_balancer_partition_samples exsistence (com.linkedin.kafka.cruisecontrol.SbkTopicUtils)
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at com.linkedin.kafka.cruisecontrol.SbkTopicUtils.checkTopicPropertiesMaybeCreate(SbkTopicUtils.java:44)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.configure(KafkaSampleStore.java:142)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1456)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:415)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1405)
	at io.confluent.databalancer.startup.StartupComponents$Builder.build(StartupComponents.java:91)
	at io.confluent.databalancer.startup.CruiseControlStartable.createKafkaCruiseControl(CruiseControlStartable.java:72)
	at io.confluent.databalancer.ConfluentDataBalanceEngine.doStart(ConfluentDataBalanceEngine.java:473)
	at io.confluent.databalancer.ConfluentDataBalanceEngine.doStart(ConfluentDataBalanceEngine.java:459)
	at io.confluent.databalancer.ConfluentDataBalanceEngine.lambda$onActivation$3(ConfluentDataBalanceEngine.java:162)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.linkedin.kafka.cruisecontrol.common.KafkaCruiseControlThreadFactory.lambda$newThread$1(KafkaCruiseControlThreadFactory.java:43)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 0.0.0.0 found
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:509)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:601)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:447)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:332)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:229)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:499)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:639)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1379)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1310)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 0.0.0.0 found
	at java.base/sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:165)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:101)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:429)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:283)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1334)
	... 19 more
```

**Comment by vdesabou** [comment]
Internal issue KAFKALESS-59
