### ISSUE TITLE
http_avro_basic_auth.sh is failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#104]
```
19:27:07 Sending messages to topic avro-topic
764[2020-09-29 19:27:11,812] ERROR Failed to send HTTP request to endpoint: http://schema-registry:8081/subjects/avro-topic-value/versions (io.confluent.kafka.schemaregistry.client.rest.RestService:267)
765java.net.UnknownHostException: schema-registry
766	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
767	at java.base/java.net.Socket.connect(Socket.java:609)
768	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
769	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
770	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
771	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
772	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
773	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
774	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
775	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
776	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
777	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
778	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
779	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
780	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:263)
781	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:352)
782	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:495)
783	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:486)
784	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:459)
785	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:206)
786	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:268)
787	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:244)
788	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:75)
789	at io.confluent.kafka.formatter.AvroMessageReader$AvroMessageSerializer.serialize(AvroMessageReader.java:168)
790	at io.confluent.kafka.formatter.SchemaMessageReader.readMessage(SchemaMessageReader.java:262)
791	at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:51)
792	at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
793org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
794Caused by: java.net.UnknownHostException: schema-registry
795	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
796	at java.base/java.net.Socket.connect(Socket.java:609)
797	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
798	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
799	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
800	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
801	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
802	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
803	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
804	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
805	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
806	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
807	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
808	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
809	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:263)
810	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:352)
811	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:495)
812	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:486)
813	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:459)
814	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:206)
815	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:268)
816	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:244)
817	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:75)
818	at io.confluent.kafka.formatter.AvroMessageReader$AvroMessageSerializer.serialize(AvroMessageReader.java:168)
819	at io.confluent.kafka.formatter.SchemaMessageReader.readMessage(SchemaMessageReader.java:262)
820	at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:51)
821	at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
```

**Comment by vdesabou** [comment]
Schema-registry logs:

```
[kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node -1 (broker/172.18.0.8:9092) could not be established. Broker may not be available.
1015[main] ERROR io.confluent.admin.utils.ClusterStatus - Error while getting broker list.
1016java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1601539625528, tries=1, nextAllowedTryMs=1601539625630) timed out at 1601539625530 after 1 attempt(s)
1017	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
1025	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
1026	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
1027	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
1028	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:149)
1029	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
1030Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1601539625528, tries=1, nextAllowedTryMs=1601539625630) timed out at 1601539625530 after 1 attempt(s)
1031Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
1032[kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node -1 (broker/172.18.0.8:9092) could not be established. Broker may not be available.
1033[main] INFO io.confluent.admin.utils.ClusterStatus - Expected 1 brokers but found only 0. Trying to query Kafka for metadata again ...
1034[main] ERROR io.confluent.admin.utils.ClusterStatus - Expected 1 brokers but found only 0. Brokers found [].
```

**Comment by vdesabou** [comment]
Weird one: schema-registry was starting up way before broker. it was fixed by setting up `restart: always`
