### ISSUE TITLE
CP 6.2.0: connect cluster does not appear in control-center

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1074]
```
[2021-06-10 08:09:32,561] ERROR Not all clusters registered successfully (io.confluent.controlcenter.data.StaticClusterMetadataInitializer)
org.apache.kafka.common.config.ConfigException: Missing required configuration "bootstrap.servers" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:507)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:497)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at org.apache.kafka.clients.admin.AdminClientConfig.<init>(AdminClientConfig.java:243)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:49)
	at io.confluent.controlcenter.kafka.DefaultAdminClientFactory.createClient(DefaultAdminClientFactory.java:11)
	at io.confluent.controlcenter.kafka.StaticClusterManager.lookupClusterId(StaticClusterManager.java:134)
	at io.confluent.controlcenter.kafka.StaticClusterManager.lambda$register$1(StaticClusterManager.java:109)
	at io.confluent.controlcenter.util.RetryUtils$1.run(RetryUtils.java:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by vdesabou** [comment]
```
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (schemaRegistryUrls, line 0)
http://127.0.0.1:9021/api/kafka-rest/CN1lIG2yTc2HCClqZgTbeQ/v1/metadata/schemaRegistryUrls
```
