### ISSUE TITLE
Azure Blob Storage Source connector 1.4.6 not working with CP 6.1.2 and CP 6.2.0

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1106]
Example: https://github.com/vdesabou/kafka-docker-playground/runs/2815046715

```log
2021-06-13T21:05:48.9309058Z [2021-06-13 21:04:43,919] ERROR WorkerConnector{id=azure-blob-source} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
2021-06-13T21:05:48.9313997Z java.util.ServiceConfigurationError: com.azure.core.http.HttpClientProvider: com.azure.core.http.netty.NettyAsyncHttpClientProvider not a subtype
2021-06-13T21:05:48.9317384Z 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
2021-06-13T21:05:48.9320294Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
2021-06-13T21:05:48.9327476Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
2021-06-13T21:05:48.9330389Z 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
2021-06-13T21:05:48.9332145Z 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
2021-06-13T21:05:48.9335514Z 	at com.azure.core.implementation.http.HttpClientProviders.<clinit>(HttpClientProviders.java:26)
2021-06-13T21:05:48.9339261Z 	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:39)
2021-06-13T21:05:48.9341566Z 	at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:60)
2021-06-13T21:05:48.9344589Z 	at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:133)
2021-06-13T21:05:48.9348235Z 	at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:113)
2021-06-13T21:05:48.9352008Z 	at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:89)
2021-06-13T21:05:48.9355432Z 	at io.confluent.connect.azure.blob.storage.AzureBlobSourceStorage.<init>(AzureBlobSourceStorage.java:74)
2021-06-13T21:05:48.9359837Z 	at io.confluent.connect.azure.blob.storage.AzureBlobStorageSourceConnector.createStorage(AzureBlobStorageSourceConnector.java:40)
2021-06-13T21:05:48.9364399Z 	at io.confluent.connect.cloud.storage.source.StorageSourceConnector.start(StorageSourceConnector.java:65)
2021-06-13T21:05:48.9367749Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:185)
2021-06-13T21:05:48.9370840Z 	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:210)
2021-06-13T21:05:48.9373799Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)
2021-06-13T21:05:48.9377019Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:332)
2021-06-13T21:05:48.9379985Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:141)
2021-06-13T21:05:48.9382776Z 	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:118)
2021-06-13T21:05:48.9385145Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-06-13T21:05:48.9387112Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-06-13T21:05:48.9389494Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-06-13T21:05:48.9392069Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-06-13T21:05:48.9393942Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-13T21:05:48.9397250Z [2021-06-13 21:04:43,933] ERROR [Worker clientId=connect-1, groupId=connect-cluster] Failed to start connector 'azure-blob-source' (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
2021-06-13T21:05:48.9401129Z org.apache.kafka.connect.errors.ConnectException: Failed to start connector: azure-blob-source
2021-06-13T21:05:48.9404393Z 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$20(DistributedHerder.java:1327)
2021-06-13T21:05:48.9408714Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:335)
2021-06-13T21:05:48.9412206Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:141)
2021-06-13T21:05:48.9415745Z 	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:118)
2021-06-13T21:05:48.9420933Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-06-13T21:05:48.9422970Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-06-13T21:05:48.9425311Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-06-13T21:05:48.9428534Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-06-13T21:05:48.9430429Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-13T21:05:48.9433377Z Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to transition connector azure-blob-source to state STARTED
2021-06-13T21:05:48.9436492Z 	... 8 more
2021-06-13T21:05:48.9440847Z Caused by: java.util.ServiceConfigurationError: com.azure.core.http.HttpClientProvider: com.azure.core.http.netty.NettyAsyncHttpClientProvider not a subtype
2021-06-13T21:05:48.9445019Z 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
2021-06-13T21:05:48.9447336Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
2021-06-13T21:05:48.9451308Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
2021-06-13T21:05:48.9453908Z 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
2021-06-13T21:05:48.9455864Z 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
2021-06-13T21:05:48.9458213Z 	at com.azure.core.implementation.http.HttpClientProviders.<clinit>(HttpClientProviders.java:26)
2021-06-13T21:05:48.9460754Z 	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:39)
2021-06-13T21:05:48.9463037Z 	at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:60)
2021-06-13T21:05:48.9466059Z 	at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:133)
2021-06-13T21:05:48.9469684Z 	at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:113)
2021-06-13T21:05:48.9473184Z 	at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:89)
2021-06-13T21:05:48.9477708Z 	at io.confluent.connect.azure.blob.storage.AzureBlobSourceStorage.<init>(AzureBlobSourceStorage.java:74)
2021-06-13T21:05:48.9482126Z 	at io.confluent.connect.azure.blob.storage.AzureBlobStorageSourceConnector.createStorage(AzureBlobStorageSourceConnector.java:40)
2021-06-13T21:05:48.9486711Z 	at io.confluent.connect.cloud.storage.source.StorageSourceConnector.start(StorageSourceConnector.java:65)
2021-06-13T21:05:48.9490362Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:185)
2021-06-13T21:05:48.9494113Z 	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:210)
2021-06-13T21:05:48.9498685Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)
2021-06-13T21:05:48.9502924Z 	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:332)
2021-06-13T21:05:48.9505763Z 	... 7 more
```

**Comment by vdesabou** [comment]
Internal ticket: https://confluentinc.atlassian.net/browse/CCMSG-1192

**Comment by vdesabou** [comment]
closing, tracked in bug
