### ISSUE TITLE
environment/mdc-plaintext failing with 5.5.2

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#111]
```
[2020-10-02 07:38:27,496] ERROR Failed to start Connect (org.apache.kafka.connect.cli.ConnectDistributed)
org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements interface org.apache.kafka.connect.rest.ConnectRestExtension and which name matches io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:436)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugins(Plugins.java:422)
	at org.apache.kafka.connect.runtime.rest.RestServer.registerRestExtensions(RestServer.java:446)
	at org.apache.kafka.connect.runtime.rest.RestServer.initializeResources(RestServer.java:238)
	at org.apache.kafka.connect.runtime.Connect.start(Connect.java:55)
	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:130)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:78)
```

**Comment by vdesabou** [comment]
It is because kafka-docker-playground-connect is picking up latest replicator version

```
root@connect-us:/usr/share/confluent-hub-components/confluentinc-kafka-connect-replicator/lib# ls replicator-
replicator-rest-extension-6.0.0.jar  
```

**Comment by vdesabou** [comment]
That should fix the issue
