### ISSUE TITLE
connect-azure-search-sink is silently failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1148]
```
[2021-06-29 09:39:21,171] ERROR Failed to start task azure-search-0 (org.apache.kafka.connect.runtime.Worker)
java.lang.NoClassDefFoundError: org/codehaus/jackson/node/ValueNode
        at io.confluent.connect.avro.AvroConverter.configure(AvroConverter.java:71)
        at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
        at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:544)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1300)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1700(DistributedHerder.java:130)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1315)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1311)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.node.ValueNode
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 11 more
```

**Comment by kundanvyas** [comment]
Hi @vdesabou . Thanks for catching this. I just ran into the same error. Did you file a bug for this internally in Confluent jira ? If not then I can go ahead and do that. Please let me know.

**Comment by kundanvyas** [comment]
Please ignore my previous message @vdesabou . I found the internal bug.
