### ISSUE TITLE
Tier storage example broken with 6.0

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#120]
```
[2020-10-06 10:22:54,402] ERROR [KafkaServer id=1] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.tier.exceptions.TierObjectStoreFatalException: Failed to access bucket aws-playground-tiered-storage
        at kafka.tier.store.S3TierObjectStore.expectBucket(S3TierObjectStore.java:256)
        at kafka.tier.store.S3TierObjectStore.<init>(S3TierObjectStore.java:65)
        at kafka.tier.store.S3TierObjectStore.<init>(S3TierObjectStore.java:52)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:411)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
        at kafka.Kafka$.main(Kafka.scala:82)
        at kafka.Kafka.main(Kafka.scala)
Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@42b6d0cc: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@51a6cc2a: Failed to connect to service endpoint: ]
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5002)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:1017)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:1023)
        at kafka.tier.store.S3TierObjectStore.expectBucket(S3TierObjectStore.java:245)
        ... 6 more
```

**Comment by vdesabou** [comment]
Can use `KAFKA_CONFLUENT_TIER_S3_CRED_FILE_PATH`or just pass `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID`
