### ISSUE TITLE
Kudu Source is failing with travis

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#124]
https://travis-ci.com/github/vdesabou/kafka-docker-playground/jobs/395959525

**Comment by vdesabou** [comment]
This is working on my laptop.

One difference is:

```
*** Running /container/run/process/slapd/run...
1005*** /container/run/process/slapd/run started as PID 496
10065f7ca83d @(#) $OpenLDAP: slapd 2.4.50+dfsg-1~bpo10+1 (May  4 2020 05:25:06) $
1007	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
10085f7ca83d slapd starting
1009	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1660)
1010	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:67)
1011	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:82)
1012	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:73)
1013	at org.apache.impala.catalog.MetaStoreClientPool$MetaStoreClient.<init>(MetaStoreClientPool.java:93)
1014	at org.apache.impala.catalog.MetaStoreClientPool$MetaStoreClient.<init>(MetaStoreClientPool.java:72)
1015	at org.apache.impala.catalog.MetaStoreClientPool.initClients(MetaStoreClientPool.java:168)
1016	at org.apache.impala.catalog.Catalog.<init>(Catalog.java:104)
1017	at org.apache.impala.catalog.CatalogServiceCatalog.<init>(CatalogServiceCatalog.java:233)
1018	at org.apache.impala.service.JniCatalog.<init>(JniCatalog.java:109)
1019Caused by: java.net.ConnectException: Connection refused (Connection refused)
1020	at java.net.PlainSocketImpl.socketConnect(Native Method)
1021	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
1022	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
1023	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
1024	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
1025	at java.net.Socket.connect(Socket.java:607)
1026	at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
1027	... 16 more
1028)
1029	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:512)
1030	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:244)
1031	... 14 more
```

**Comment by vdesabou** [comment]
https://travis-ci.com/github/vdesabou/kafka-docker-playground/jobs/396252284

**Comment by vdesabou** [comment]
I think it is due to host.docker.internal being used in kudu image [here](https://github.com/NathanNam/all-in-one-docker-impala-kudu/blob/57cc92b6d8c3f7bc4c4e87237fb89b09b8689d14/default/impala#L9)

Would need to apply something like https://dev.to/natterstefan/docker-tip-how-to-get-host-s-ip-address-inside-a-docker-container-5anh

**Comment by vdesabou** [comment]
```
2020-10-08 09:21:54,789 WARN org.apache.hadoop.hdfs.server.namenode.FSNamesystem: Encountered exception loading fsimage
org.apache.hadoop.hdfs.server.common.InconsistentFSStateException: Directory /var/lib/hadoop-hdfs/cache/hdfs/dfs/name is in an inconsistent state: storage directory does not exist or is not accessible.
        at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverStorageDirs(FSImage.java:377)
        at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:228)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:1152)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:799)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:614)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:676)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:844)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:823)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1547)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1615)
2020-10-08 09:21:54,791 INFO org.mortbay.log: Stopped HttpServer2$SelectChannelConnectorWithSafeStartup@0.0.0.0:50070
2020-10-08 09:21:54,892 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Stopping NameNode metrics system...
2020-10-08 09:21:54,892 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: NameNode metrics system stopped.
2020-10-08 09:21:54,892 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: NameNode metrics system shutdown complete.
2020-10-08 09:21:54,892 ERROR org.apache.hadoop.hdfs.server.namenode.NameNode: Failed to start namenode.
org.apache.hadoop.hdfs.server.common.InconsistentFSStateException: Directory /var/lib/hadoop-hdfs/cache/hdfs/dfs/name is in an inconsistent state: storage directory does not exist or is not accessible.
        at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverStorageDirs(FSImage.java:377)
        at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:228)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:1152)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:799)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:614)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:676)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:844)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:823)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1547)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1615)
2020-10-08 09:21:54,894 INFO org.apache.hadoop.util.ExitUtil: Exiting with status 1
2020-10-08 09:21:54,895 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at 277a6687add6/172.17.0.2
************************************************************/
```

**Comment by vdesabou** [comment]
The error above is because I did not build with correct ulimit:

```
docker build --ulimit nofile=100000:100000 . -t vdesabou/kudu-impala-with-ldap
```
