### ISSUE TITLE
AWS Redshift failing with Travis

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#127]
```
17:48:29 Waiting up to 480 seconds for AWS Redshift cluster playgroundcluster to start
278617:50:59 AWS Redshift cluster playgroundcluster has started!
2787  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2788                                 Dload  Upload   Total   Spent    Left  Speed
2789100    13  100    13    0     0    125      0 --:--:-- --:--:-- --:--:--   126
279017:50:59 Create a security group
279117:51:02 Allow ingress traffic from public ip on port 5439
279217:51:03 Modify AWS Redshift cluster to use the security group
2793{
2794    "Cluster": {
2795        "ClusterIdentifier": "playgroundcluster",
2796        "NodeType": "dc2.large",
2797        "ClusterStatus": "available",
2798        "ClusterAvailabilityStatus": "Available",
2799        "MasterUsername": "masteruser",
2800        "DBName": "dev",
2801        "Endpoint": {
2802            "Address": "playgroundcluster.ch0ou1z9c3sj.eu-west-3.redshift.amazonaws.com",
2803            "Port": 5439
2804        },
2805        "ClusterCreateTime": "2020-10-06T17:50:53.456Z",
2806        "AutomatedSnapshotRetentionPeriod": 1,
2807        "ManualSnapshotRetentionPeriod": -1,
2808        "ClusterSecurityGroups": [],
2809        "VpcSecurityGroups": [
2810            {
2811                "VpcSecurityGroupId": "sg-03c2493f53087f9d3",
2812                "Status": "adding"
2813            },
2814            {
2815                "VpcSecurityGroupId": "sg-955b0afe",
2816                "Status": "removing"
2817            }
2818        ],
2819        "ClusterParameterGroups": [
2820            {
2821                "ParameterGroupName": "default.redshift-1.0",
2822                "ParameterApplyStatus": "in-sync"
2823            }
2824        ],
2825        "ClusterSubnetGroupName": "default",
2826        "VpcId": "vpc-a2bb9bcb",
2827        "AvailabilityZone": "eu-west-3b",
2828        "PreferredMaintenanceWindow": "fri:15:00-fri:15:30",
2829        "PendingModifiedValues": {},
2830        "ClusterVersion": "1.0",
2831        "AllowVersionUpgrade": true,
2832        "NumberOfNodes": 1,
2833        "PubliclyAccessible": true,
2834        "Encrypted": false,
2835        "Tags": [],
2836        "EnhancedVpcRouting": false,
2837        "IamRoles": [],
2838        "MaintenanceTrackName": "current",
2839        "DeferredMaintenanceWindows": [],
2840        "NextMaintenanceWindowStartTime": "2020-10-09T15:00:00Z"
2841    }
2842}
284317:51:08 Sending messages to topic orders
284417:51:12 Creating AWS Redshift Logs Source connector
2845  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2846                                 Dload  Upload   Total   Spent    Left  Speed
2847100  1334  100   562  100   772    658    904 --:--:-- --:--:-- --:--:--   903
2848{
2849  "name": "redshift-sink",
2850  "config": {
2851    "connector.class": "io.confluent.connect.aws.redshift.RedshiftSinkConnector",
2852    "tasks.max": "1",
2853    "topics": "orders",
2854    "aws.redshift.domain": "playgroundcluster.ch0ou1z9c3sj.eu-west-3.redshift.amazonaws.com",
2855    "aws.redshift.port": "5439",
2856    "aws.redshift.database": "dev",
2857    "aws.redshift.user": "masteruser",
2858    "aws.redshift.password": "myPassword1",
2859    "auto.create": "true",
2860    "pk.mode": "kafka",
2861    "confluent.license": "",
2862    "confluent.topic.bootstrap.servers": "broker:9092",
2863    "confluent.topic.replication.factor": "1",
2864    "name": "redshift-sink"
2865  },
2866  "tasks": [],
2867  "type": "sink"
2868}
```

**Comment by vdesabou** [comment]
https://travis-ci.com/github/vdesabou/kafka-docker-playground/jobs/395963549

```
[2020-10-06 20:11:03,947] INFO Unable to connect to database on attempt 1/3. Will retry in 10000 ms. (io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider)
3494java.sql.SQLException: [Amazon](500150) Error setting/closing connection: Connection timed out.
3495	at com.amazon.redshift.client.PGClient.connect(Unknown Source)
3496	at com.amazon.redshift.client.PGClient.<init>(Unknown Source)
3497	at com.amazon.redshift.core.PGJDBCConnection.connect(Unknown Source)
3498	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
3499	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
3500	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
3501	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
3502	at io.confluent.connect.aws.redshift.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:211)
3503	at io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:88)
3504	at io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
3505	at io.confluent.connect.aws.redshift.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
3506	at io.confluent.connect.aws.redshift.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
3507	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
3508	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
3509	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
3510	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
3511	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
3512	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
3513	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
3514	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
3515	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
3516	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
3517Caused by: com.amazon.support.exceptions.GeneralException: [Amazon](500150) Error setting/closing connection: Connection timed out.
3518	... 22 more
3519Caused by: java.net.ConnectException: Connection timed out
3520	at java.base/sun.nio.ch.Net.connect0(Native Method)
3521	at java.base/sun.nio.ch.Net.connect(Net.java:476)
3522	at java.base/sun.nio.ch.Net.connect(Net.java:468)
3523	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
3524	at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:100)
3525	at com.amazon.redshift.client.PGClient.connect(Unknown Source)
3526	at com.amazon.redshift.client.PGClient.<init>(Unknown Source)
3527	at com.amazon.redshift.core.PGJDBCConnection.connect(Unknown Source)
3528	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
3529	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
3530	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
3531	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
3532	at io.confluent.connect.aws.redshift.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:211)
3533	at io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:88)
3534	at io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:62)
3535	at io.confluent.connect.aws.redshift.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
3536	at io.confluent.connect.aws.redshift.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
3537	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
3538	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
3539	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
3540	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
3541	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
3542	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
3543	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
3544	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
3545	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
3546	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
3547	at java.base/java.lang.Thread.run(Thread.java:834)
3548[2020-10-06 20:11:13,949] INFO Attempting to open connection #2 to Redshift (io.confluent.connect.aws.redshift.jdbc.util.CachedConnectionProvider)
```

**Comment by vdesabou** [comment]
Travis job is running on GCE. In order to make it work, it would have to be run on AWS and apply [this](https://docs.aws.amazon.com/redshift/latest/mgmt/getting-started-cli.html):

![Screenshot 2020-10-07 at 14 53 37](https://user-images.githubusercontent.com/4061923/95333443-17682e00-08ad-11eb-843a-40ae012212b8.png)

I'll skip it from Travis
