### ISSUE TITLE
Salesforce Bulk API and SObject Sink are failing silently

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#140]
```
[2020-10-29 11:45:41,817] ERROR WorkerSinkTask{id=salesforce-bulkapi-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
1672org.apache.kafka.connect.errors.ConnectException: Unable to describe Lead
1673	at io.confluent.connect.salesforce.SalesforceBulkApiSinkTask.updateFieldInformations(SalesforceBulkApiSinkTask.java:254)
1674	at io.confluent.connect.salesforce.SalesforceBulkApiSinkTask.start(SalesforceBulkApiSinkTask.java:103)
1675	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:302)
1676	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
1677	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
1678	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
1679	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1680	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1681	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1682	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1683	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://travis-ci.com/github/vdesabou/kafka-docker-playground/jobs/418401942

**Comment by vdesabou** [comment]
connect/connect-salesforce-bulkapi-sink[salesforce-bulkapi-sink-with-bulkapi-source.sh]
connect/connect-salesforce-bulkapi-sink[salesforce-bulkapi-sink-with-pushtopics-source.sh]
connect/connect-salesforce-sobject-sink[salesforce-sobject-sink.sh]

https://travis-ci.com/github/vdesabou/kafka-docker-playground/jobs/418990059#L3876

**Comment by vdesabou** [comment]
I needed to update my password on Salesforce
