### ISSUE TITLE
🔥 other/cluster-linking

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1495]
🆕💥 New issue !

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-05 17:41 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119238588?check_suite_focus=true

**Comment by vdesabou** [comment]
🤦‍♂️💥 Still failing !

👍 CP 5.3.6 🕐 2021-11-06 15:20 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4125395399?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-06 20:51 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null

**Comment by vdesabou** [comment]
🤦‍♂️💥 Still failing !

👍 CP 5.3.6 🕐 2021-11-06 15:20 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4125395399?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-07 17:56 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null

**Comment by vdesabou** [comment]
🤦‍♂️💥 Still failing !

👍 CP 5.3.6 🕐 2021-11-06 15:20 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4125395399?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-08 10:25 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null

**Comment by vdesabou** [comment]
🤦‍♂️💥 Still failing !

👍 CP 5.3.6 🕐 2021-11-06 15:20 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4125395399?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-08 20:59 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null

**Comment by vdesabou** [comment]
🤦‍♂️💥 Still failing !

👍 CP 5.3.6 🕐 2021-11-06 15:20 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4125395399?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-09 16:34 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null

**Comment by vdesabou** [comment]
🤦‍♂️💥 Still failing !

👍 CP 5.3.6 🕐 2021-11-06 15:20 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4125395399?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-09 17:08 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null

**Comment by vdesabou** [comment]
```
15:55:59 ℹ️ Create the cluster link on the destination cluster (with metadata.max.age.ms=5 seconds + consumer.offset.sync.enable=true + consumer.offset.sync.ms=3000 + consumer.offset.sync.all.json set to all consumer groups)
Error while executing cluster link command: link-name is not a recognized option
[2021-11-10 15:56:01,466] ERROR joptsimple.UnrecognizedOptionException: link-name is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
        at joptsimple.OptionParser.parse(OptionParser.java:396)
        at kafka.admin.ClusterLinkCommandOptions.<init>(ClusterLinkCommand.scala:272)
        at kafka.admin.ClusterLinkCommand$.run(ClusterLinkCommand.scala:126)
        at kafka.admin.ClusterLinkCommand$.main(ClusterLinkCommand.scala:24)
        at kafka.admin.ClusterLinkCommand.main(ClusterLinkCommand.scala)
 (kafka.admin.ClusterLinkCommand$)
```

**Comment by vdesabou** [comment]
🤦‍♂️💥 Still failing !

👍 CP 5.3.6 🕐 2021-11-06 15:20 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4125395399?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-05 16:18 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119230586?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-05 16:28 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119232143?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-05 16:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119233711?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-05 16:57 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119235310?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-05 17:15 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4119237009?check_suite_focus=true

🔥 CP 7.0.0 🕐 2021-11-10 17:42 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null

**Comment by vdesabou** [comment]
👍✅ Issue fixed !

👍 CP 5.3.6 🕐 2021-11-10 20:17 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4170316429?check_suite_focus=true

👍 CP 5.4.5 🕐 2021-11-10 20:35 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4170317875?check_suite_focus=true

👍 CP 5.5.6 🕐 2021-11-10 20:58 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4170319517?check_suite_focus=true

👍 CP 6.0.4 🕐 2021-11-10 21:06 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4170321130?check_suite_focus=true

👍 CP 6.1.3 🕐 2021-11-10 21:17 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4170322526?check_suite_focus=true

👍 CP 6.2.1 🕐 2021-11-10 21:24 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 https://github.com/vdesabou/kafka-docker-playground/runs/4170323979?check_suite_focus=true

👍 CP 7.0.0 🕐 2021-11-10 21:58 📄 [start.sh](https://github.com/vdesabou/kafka-docker-playground/blob/master/other/cluster-linking/start.sh) 🔗 null
