### ISSUE TITLE
Add Apache HBase Sink example with proxy

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1687]
https://docs.confluent.io/kafka-connect-hbase/current/overview.html#proxy-settings

**Comment by vdesabou** [comment]
```
[2021-11-16 15:52:24,919] ERROR [hbase-sink-proxy3|task-0] hconnection-0x726b6a1d0x0, quorum=hbase:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception (org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher:739)
org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1102)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:284)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:468)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:944)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:720)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:649)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at org.apache.hadoop.hbase.client.HBaseAdmin.checkHBaseAvailable(HBaseAdmin.java:3276)
        at io.confluent.connect.hbase.client.HBaseConnectionProvider.checkAndReturnConnection(HBaseConnectionProvider.java:84)
        at io.confluent.connect.hbase.client.HBaseConnectionProvider.newConnection(HBaseConnectionProvider.java:73)
        at io.confluent.connect.hbase.client.HBaseConnectionProvider.newConnection(HBaseConnectionProvider.java:24)
        at io.confluent.connect.bigtable.BaseBigtableSinkTask.setupConnection(BaseBigtableSinkTask.java:147)
        at io.confluent.connect.bigtable.BaseBigtableSinkTask.start(BaseBigtableSinkTask.java:52)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:305)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:239)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by vdesabou** [comment]
I’m wondering if it can really work since the proxy code is for HTTP traffic (at least how I understand it), whereas I’m really not sure HTTP is used for HBase, right ?
Maybe the documentation is there because HBase is sharing common code with GCP BigTable sink?
