### ISSUE TITLE
CI: other/write-logs-to-files failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#182]
```
ERROR: for ksqldb-server  Cannot start service ksqldb-server: driver failed programming external connectivity on endpoint ksqldb-server (4b4515194119597d1caa48d9a6cd02231b269db576d2a28046e4fe9df1d28d9e): Bind for 0.0.0.0:8088 failed: port is already allocated
```

**Comment by vdesabou** [comment]
```
log4j:ERROR setFile(null,true) call failed.
948
java.io.FileNotFoundException: /var/log/broker/server.log (Permission denied)
949
	at java.base/java.io.FileOutputStream.open0(Native Method)
950
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
951
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
952
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
953
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
954
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
955
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
956
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
957
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
958
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
959
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
960
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
961
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
962
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
963
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
964
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
965
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
966
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
967
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
968
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
969
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
970
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
971
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
972
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
973
	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:48)
974
	at kafka.utils.Log4jControllerRegistration$.<clinit>(Logging.scala:25)
975
	at kafka.Kafka$.<clinit>(Kafka.scala:30)
976
	at kafka.Kafka.main(Kafka.scala)
```
