### ISSUE TITLE
cp-ansible-playground: control-center not working

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1880]
```
confluent-control-center.service: [2021-12-10 15:23:46,213] ERROR Unexpected error (io.confluent.controlcenter.ControlCenter)
confluent-control-center.service: org.apache.kafka.streams.errors.InvalidStateStoreException: The state store, commander, may have migrated to another instance.
confluent-control-center.service:       at org.apache.kafka.streams.state.internals.WrappingStoreProvider.stores(WrappingStoreProvider.java:66)
confluent-control-center.service:       at org.apache.kafka.streams.state.internals.CompositeReadOnlyKeyValueStore.all(CompositeReadOnlyKeyValueStore.java:140)
confluent-control-center.service:       at io.confluent.controlcenter.command.CommandMigrator.getActiveControllerCountTriggers(CommandMigrator.java:132)
confluent-control-center.service:       at io.confluent.controlcenter.command.CommandMigrator.disableActionsForActiveControllerCountTrigger(CommandMigrator.java:97)
confluent-control-center.service:       at io.confluent.controlcenter.command.CommandMigrator.migrate(CommandMigrator.java:57)
confluent-control-center.service:       at io.confluent.controlcenter.ControlCenter.main(ControlCenter.java:139)
```

**Comment by vdesabou** [comment]
fixed by baae068

![CleanShot 2021-12-13 at 15 59 45](https://user-images.githubusercontent.com/4061923/145835644-9319336a-cff4-4323-9a6a-6876fdea4a64.jpg)
