### ISSUE TITLE
CI: replicator/executable are failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#191]
https://github.com/vdesabou/kafka-docker-playground/runs/1733608460?check_suite_focus=true

**Comment by vdesabou** [comment]
Now getting:


```
[2021-01-22 11:03:43,172] ERROR WorkerConnector{id=replicator} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:441)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:273)
        at org.apache.kafka.connect.util.KafkaBasedLog.createProducer(KafkaBasedLog.java:256)
        at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:131)
        at io.confluent.license.LicenseStore.startLog(LicenseStore.java:259)
        at io.confluent.license.LicenseStore.start(LicenseStore.java:245)
        at io.confluent.license.LicenseManager.<init>(LicenseManager.java:225)
        at io.confluent.license.LicenseManager.<init>(LicenseManager.java:207)
        at io.confluent.license.LicenseManager.<init>(LicenseManager.java:147)
        at io.confluent.connect.replicator.ReplicatorSourceConnector.validateLicense(ReplicatorSourceConnector.java:195)
        at io.confluent.connect.replicator.ReplicatorSourceConnector.start(ReplicatorSourceConnector.java:91)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:186)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:211)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:350)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:333)
        at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:141)
        at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:118)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.KafkaException: Could not instantiate class io.confluent.license.LicenseStore$LicenseKeySerde
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:351)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:377)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:399)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:366)
        ... 21 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:347)
        ... 24 more
Caused by: java.lang.IncompatibleClassChangeError: Class io.confluent.command.record.Command$CommandKey does not implement the requested interface com.google.protobuf.Message
        at io.confluent.serializers.ProtoSerde.<init>(ProtoSerde.java:37)
        at io.confluent.license.LicenseStore$LicenseKeySerde.<init>(LicenseStore.java:232)
        ... 29 more
[2021-01-22 11:03:43,195] ERROR [Worker clientId=dest-client-id-replicate-europe-to-us, groupId=replicator] Failed to start connector 'replicator' (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
org.apache.kafka.connect.errors.ConnectException: Failed to start connector: replicator
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$5(DistributedHerder.java:1304)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:336)
        at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:141)
        at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:118)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vdesabou** [comment]
Previous issue was because I was overriding connect container with replicator executable one

**Comment by vdesabou** [comment]
With latest commit, I get for sasl-plain:

```
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:521)
        at org.apache.kafka.clients.admin.Admin.create(Admin.java:73)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:52)
        at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.configure(KafkaOffsetBackingStore.java:72)
        at io.confluent.connect.replicator.ReplicatorApp.config(ReplicatorApp.java:131)
        at io.confluent.connect.replicator.ReplicatorApp.main(ReplicatorApp.java:76)
Caused by: java.lang.IllegalArgumentException: Login module control flag not specified in JAAS config
        at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:110)
        at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:100)
        at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:94)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:134)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:73)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:496)
        ... 5 more
```

which is weird because config looks good:

```
[appuser@replicator-europe ~]$ cat /etc/replicator/consumer.properties
bootstrap.servers=broker-us:9092
client.id=source-client-id-replicate-us-to-europe
group.id=source-group-id-replicate-us-to-europe

security.protocol=SASL_PLAINTEXT
sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required  username=client password=client-secret;"
sasl.mechanism=PLAIN
[appuser@replicator-europe ~]$ cat /etc/replicator/producer.properties
bootstrap.servers=broker-europe:9092
client.id=dest-client-id-replicate-us-to-europe
group.id=dest-group-id-replicate-us-to-europe

security.protocol=SASL_PLAINTEXT
sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required  username=client password=client-secret;"
sasl.mechanism=PLAIN
```

**Comment by vdesabou** [comment]
☝ Needed to remove quotes:

```
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required  username=client password=client-secret;
```
