### ISSUE TITLE
CI: connect-salesforce-bulkapi-sink failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#199]
```
[2021-01-29 14:14:19,680] ERROR WorkerSinkTask{id=salesforce-bulkapi-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
895
org.apache.kafka.connect.errors.ConnectException: Unable to describe Lead
896
	at io.confluent.connect.salesforce.SalesforceBulkApiSinkTask.updateFieldInformations(SalesforceBulkApiSinkTask.java:254)
897
	at io.confluent.connect.salesforce.SalesforceBulkApiSinkTask.start(SalesforceBulkApiSinkTask.java:103)
898
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:305)
899
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
900
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
901
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
902
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
903
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
904
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
905
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
906
	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://github.com/vdesabou/kafka-docker-playground/runs/1792049792?check_suite_focus=true

**Comment by vdesabou** [comment]
There was a successful build with `1.7.11` 

```
02:07:21 ####################################################
101
02:07:21 Skipping as test with CP 6.0.1 and connector 1.7.11 has already been executed successfully 6 days 20 hours 50 minutes and 7 seconds ago
102
02:07:21 ####################################################
103
Completed 58 Bytes/58 Bytes (131 Bytes/s) with 1 file(s) remaining
104
download: s3://kafka-docker-playground/ci/6.0.1-connect-connect-salesforce-bulkapi-sink-1.7.11-salesforce-bulkapi-sink-with-pushtopics-source.sh to ./6.0.1-connect-connect-salesforce-bulkapi-sink-1.7.11-salesforce-bulkapi-sink-with-pushtopics-source.sh
105
02:07:24 ####################################################
106
02:07:24 Skipping as test with CP 6.0.1 and connector 1.7.11 has already been executed successfully 6 days 20 hours 47 minutes and 51 seconds ago
107
02:07:24 ####################################################
```

**Comment by vdesabou** [comment]
I needed to change SALESFORCE_PASSWORD_ACCOUNT2 and SECURITY_TOKEN_ACCOUNT2
