### ISSUE TITLE
connect/connect-debezium-postgresql-source[postgres.sh] failing with 5.5.3

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#220]
https://github.com/vdesabou/kafka-docker-playground/runs/2054571430?check_suite_focus=true

```
[2021-03-08 07:55:31,376] ERROR WorkerSourceTask{id=debezium-postgres-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
940
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
941
	at io.debezium.connector.postgresql.connection.Lsn.valueOf(Lsn.java:86)
942
	at io.debezium.connector.postgresql.spi.SlotCreationResult.<init>(SlotCreationResult.java:24)
943
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.parseSlotCreation(PostgresReplicationConnection.java:375)
944
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.createReplicationSlot(PostgresReplicationConnection.java:356)
945
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:127)
946
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:106)
947
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:219)
948
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
949
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
950
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
951
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
952
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
953
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
954
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vdesabou** [comment]
https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

**Comment by vdesabou** [comment]
https://issues.redhat.com/browse/DBZ-2870

**Comment by vdesabou** [comment]
This is happening with JDK 1.8 and using debezium version 1.3.1 and 1.4.0

**Comment by vdesabou** [comment]
duplicate by https://github.com/vdesabou/kafka-docker-playground/issues/782
