### ISSUE TITLE
replicator/executable failing with 5.5.3

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#222]
https://github.com/vdesabou/kafka-docker-playground/runs/2054571702?check_suite_focus=true

**Comment by vdesabou** [comment]
```
[2021-03-09 09:42:45,530] ERROR WorkerConnector{id=replicator} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:434)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:270)
        at org.apache.kafka.connect.util.KafkaBasedLog.createProducer(KafkaBasedLog.java:256)
        at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:131)
        at io.confluent.license.LicenseStore.startLog(LicenseStore.java:259)
        at io.confluent.license.LicenseStore.start(LicenseStore.java:245)
        at io.confluent.license.LicenseManager.<init>(LicenseManager.java:201)
        at io.confluent.license.LicenseManager.<init>(LicenseManager.java:185)
        at io.confluent.license.LicenseManager.<init>(LicenseManager.java:143)
        at io.confluent.connect.replicator.ReplicatorSourceConnector.validateLicense(ReplicatorSourceConnector.java:208)
        at io.confluent.connect.replicator.ReplicatorSourceConnector.start(ReplicatorSourceConnector.java:96)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:266)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1236)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:127)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1252)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1248)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: Could not instantiate class io.confluent.license.LicenseStore$LicenseKeySerde
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:361)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:370)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:392)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:359)
        ... 22 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:357)
        ... 25 more
Caused by: java.lang.IncompatibleClassChangeError: Class io.confluent.command.record.Command$CommandKey does not implement the requested interface com.google.protobuf.Message
        at io.confluent.serializers.ProtoSerde.<init>(ProtoSerde.java:37)
        at io.confluent.license.LicenseStore$LicenseKeySerde.<init>(LicenseStore.java:232)
        ... 30 more
```

**Comment by vdesabou** [comment]
Internal issue tracking this: REPL-1531

**Comment by vdesabou** [comment]
```
root         1     0 13 13:43 ?        00:01:18 java -Xms256M -Xmx2G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -Djava.awt.headless=true -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dlog4j.configuration=file:/etc/kafka-connect-replicator/replicator-log4j.properties -cp /etc/kafka-connect/jars/*:/usr/share/java/kafka-connect-replicator/replicator-rest-extension-5.5.3.jar:/usr/share/java/monitoring-interceptors/monitoring-interceptors-5.5.3.jar:/usr/share/java/kafka-connect-replicator/*:/usr/share/java/confluent-security/connect/*:/usr/share/java/kafka/*:/usr/share/java/confluent-common/*:/usr/share/java/kafka-serde-tools/*:/usr/share/java/monitoring-interceptors/* io.confluent.connect.replicator.ReplicatorApp --consumer.config /etc/replicator/consumer.properties --producer.config /etc/replicator/producer.properties --cluster.id replicator --replication.config /etc/replicator/replication.properties --whitelist sales_EUROPE
```

**Comment by vdesabou** [comment]
duplicate by https://github.com/vdesabou/kafka-docker-playground/issues/790
