### ISSUE TITLE
ccloud/schema-registry-security-plugin failing with 5.5.3

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#223]
https://github.com/vdesabou/kafka-docker-playground/runs/2054571787?check_suite_focus=true

```
[2021-03-08 07:51:56,654] ERROR Failed to deserialize the value (io.confluent.kafka.schemaregistry.security.authorizer.schemaregistryacl.SchemaRegistryAclReaderThread)
542
io.confluent.kafka.schemaregistry.storage.exceptions.SerializationException: Error while deserializing SchemaRegistryAclValue
543
	at io.confluent.kafka.schemaregistry.security.authorizer.schemaregistryacl.AclMessageSerializer.deserializeSchemaRegistryAclValue(AclMessageSerializer.java:125)
544
	at io.confluent.kafka.schemaregistry.security.authorizer.schemaregistryacl.SchemaRegistryAclReaderThread.handleSchemaRegistryAclValue(SchemaRegistryAclReaderThread.java:171)
545
	at io.confluent.kafka.schemaregistry.security.authorizer.schemaregistryacl.SchemaRegistryAclReaderThread.doWork(SchemaRegistryAclReaderThread.java:145)
546
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
547
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `io.confluent.kafka.schemaregistry.security.authorizer.SchemaRegistryResourceOperation` from String "GLOBAL_READ": not one of the values accepted for Enum class: [GLOBAL_COMPATIBILITY_READ, GLOBAL_SUBJECTS_READ, GLOBAL_COMPATIBILITY_WRITE, SUBJECT_COMPATIBILITY_READ, SUBJECT_READ, SUBJECT_WRITE, SUBJECT_COMPATIBILITY_WRITE, SUBJECT_DELETE, AUTHORIZATION_NOT_REQUIRED, SCHEMA_READ]
548
 at [Source: (byte[])"{"magic":0,"principal":"admin","allowedoperations":["GLOBAL_COMPATIBILITY_READ","GLOBAL_COMPATIBILITY_WRITE","GLOBAL_READ"]}"; line: 1, column: 110] (through reference chain: io.confluent.kafka.schemaregistry.security.authorizer.schemaregistryacl.GlobalAclValue["allowedoperations"]->java.util.HashSet[2])
549
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
550
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1679)
551
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:935)
552
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
553
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
554
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
555
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
556
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
557
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
558
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
559
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
560
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1292)
561
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
562
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
563
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
564
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3275)
565
	at io.confluent.kafka.schemaregistry.security.authorizer.schemaregistryacl.AclMessageSerializer.deserializeSchemaRegistryAclValue(AclMessageSerializer.java:117)
566
	... 3 more
```

**Comment by vdesabou** [comment]
GLOBAL_SUBJECTS_READ replaced by GLOBAL_READ in CP 6.0.x

But not executing with 5.5.3 because Zookeeper seems mandatory for license (getting A HostProvider may not be empty)
