### ISSUE TITLE
NPE with GCS Source connector

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#26]
To investigate:

```
er)
[2020-05-19 12:30:11,574] ERROR WorkerSourceTask{id=GCSSourceConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NullPointerException
        at io.confluent.connect.cloud.storage.source.StorageSourceTask.start(StorageSourceTask.java:73)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:213)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-05-19 12:30:11,577] ERROR WorkerSourceTask{id=GCSSourceConnector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-05-19 12:30:11,577] INFO Stopping source connector task with assigned folders null (io.confluent.connect.cloud.storage.source.StorageSourceTask)
```

**Comment by vdesabou** [comment]
This is fixed in latest version available on Confluent Hub
