### ISSUE TITLE
connect-azure-blob-storage-source failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#28]
```
[2020-05-18 15:43:02,577] ERROR WorkerConnector{id=azure-blob-source} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
2122java.lang.LinkageError: loader constraint violation: when resolving method "com.fasterxml.jackson.databind.module.SimpleModule.<init>(Lcom/fasterxml/jackson/core/Version;)V" the class loader (instance of org/apache/kafka/connect/runtime/isolation/PluginClassLoader) of the current class, com/fasterxml/jackson/datatype/jsr310/JavaTimeModule, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, com/fasterxml/jackson/databind/module/SimpleModule, have different Class objects for the type com/fasterxml/jackson/core/Version used in the signature
2123	at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:113)
2124	at com.azure.core.util.serializer.JacksonAdapter.initializeObjectMapper(JacksonAdapter.java:261)
2125	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:75)
2126	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:109)
2127	at com.azure.core.http.rest.RestProxy.createDefaultSerializer(RestProxy.java:613)
2128	at com.azure.core.http.rest.RestProxy.create(RestProxy.java:665)
2129	at com.azure.storage.blob.implementation.ServicesImpl.<init>(ServicesImpl.java:58)
2130	at com.azure.storage.blob.implementation.AzureBlobStorageImpl.<init>(AzureBlobStorageImpl.java:216)
2131	at com.azure.storage.blob.implementation.AzureBlobStorageBuilder.build(AzureBlobStorageBuilder.java:93)
2132	at com.azure.storage.blob.BlobServiceAsyncClient.<init>(BlobServiceAsyncClient.java:110)
2133	at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:109)
2134	at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:82)
2135	at io.confluent.connect.azure.blob.storage.AzureBlobSourceStorage.<init>(AzureBlobSourceStorage.java:95)
2136	at io.confluent.connect.azure.blob.storage.AzureBlobStorageSourceConnector.createStorage(AzureBlobStorageSourceConnector.java:51)
2137	at io.confluent.connect.cloud.storage.source.StorageSourceConnector.start(StorageSourceConnector.java:64)
2138	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
2139	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
2140	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
2141	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:264)
2142	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1190)
2143	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:126)
2144	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1206)
2145	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1202)
2146	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2147	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2148	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2149	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vdesabou** [comment]
Now fixed in `1.3.2`
