### ISSUE TITLE
connect-aws-kinesis-source failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#29]
```
[2020-05-18 16:37:56,135] ERROR WorkerConnector{id=kinesis-source} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
1559java.lang.LinkageError: loader constraint violation: when resolving overridden method "io.confluent.command.record.Command$CommandKey.getDefaultInstanceForType()Lcom/google/protobuf/Message;" the class loader (instance of org/apache/kafka/connect/runtime/isolation/PluginClassLoader) of the current class, io/confluent/command/record/Command$CommandKey, and its superclass loader (instance of sun/misc/Launcher$AppClassLoader), have different Class objects for the type com/google/protobuf/Message used in the signature
1560	at io.confluent.license.LicenseStore.<clinit>(LicenseStore.java:57)
1561	at io.confluent.license.LicenseManager.<init>(LicenseManager.java:141)
1562	at io.confluent.connect.utils.licensing.ConnectLicenseManager$Builder.lambda$build$0(ConnectLicenseManager.java:210)
1563	at io.confluent.connect.utils.licensing.ConnectLicenseManager.registerOrValidateLicense(ConnectLicenseManager.java:255)
1564	at io.confluent.connect.kinesis.KinesisSourceConnector.doStart(KinesisSourceConnector.java:55)
1565	at io.confluent.connect.kinesis.KinesisSourceConnector.start(KinesisSourceConnector.java:46)
1566	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
1567	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
1568	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
1569	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:264)
1570	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1190)
1571	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:126)
1572	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1206)
1573	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1202)
1574	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
1575	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
1576	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
1577	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vdesabou** [comment]
This is fixed in latest version available on Confluent Hub
