### ISSUE TITLE
connect-cassandra-sink is failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#33]
```
[2020-06-12 07:50:53,201] ERROR WorkerConnector{id=cassandra-sink} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
1228java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
1229	at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:136)
1230	at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:52)
1231	at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:71)
1232	at io.confluent.connect.cassandra.CassandraSessionFactoryImpl.newSession(CassandraSessionFactoryImpl.java:44)
1233	at io.confluent.connect.cassandra.CassandraSinkConnector.doStart(CassandraSinkConnector.java:52)
1234	at io.confluent.connect.cassandra.CassandraSinkConnector.start(CassandraSinkConnector.java:45)
1235	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
1236	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
1237	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
1238	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:264)
1239	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1190)
1240	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:126)
1241	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1206)
1242	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1202)
1243	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
1244	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
1245	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
1246	at java.lang.Thread.run(Thread.java:748)
1247Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
1248	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
1249	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
1250	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
1251	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
1252	... 18 more
```

**Comment by vdesabou** [comment]
Fixed
