### ISSUE TITLE
Adapt playground to M1 mac

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#3488]
- [ ] reiz/nginx_proxy
- [ ] kafka-lag-exporter
- [ ] google/cloud-sdk --> Only cloud-cli images seem to have arm64 support, not cloud-sdk images.
- [ ] ibmcom/mq --> [not available](https://integration-development.ideas.ibm.com/ideas/MESNS-I-369)
- [ ] mcr.microsoft.com/azure-cli --> will be released in version in 2.46 ([source](https://github.com/Azure/azure-cli/issues/7368))
- [ ] oracle image --> https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/FAQ.md#can-i-run-oracle-database-containers-on-apple-m1-arm-devices

**Comment by vdesabou** [comment]
For sqlserver:

```
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Password!"
```

```
docker exec -i sqlserver bash << EOF
mkdir -p /opt/mssql-tools/bin && cd /opt/mssql-tools/bin && wget https://github.com/microsoft/go-sqlcmd/releases/download/v0.8.0/sqlcmd-v0.8.0-linux-arm64.tar.bz2 && bzip2 -d sqlcmd-v0.8.0-linux-arm64.tar.bz2 && tar -xvf sqlcmd-v0.8.0-linux-arm64.tar && chmod 755 sqlcmd
EOF

log "Create table"
docker exec -e SQLCMDPASSWORD='Password!' -i sqlserver /opt/mssql-tools/bin/sqlcmd -U sa << EOF

EXEC sp_configure 'clr enabled', 1;  
RECONFIGURE;  
GO 
```

```
[2023-03-05 20:12:57,803] WARN [debezium-sqlserver-source|task-0] WorkerSourceTask{id=debezium-sqlserver-source-0} failed to poll records from SourceTask. Will retry operation. (org.apache.kafka.connect.runtime.AbstractWorkerSourceTask:472)
org.apache.kafka.connect.errors.RetriableException: An exception occurred in the change event producer. This connector will be restarted.
        at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:49)
        at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.executeIteration(SqlServerStreamingChangeEventSource.java:333)
        at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.executeIteration(SqlServerStreamingChangeEventSource.java:60)
        at io.debezium.connector.sqlserver.SqlServerChangeEventSourceCoordinator.executeChangeEventSources(SqlServerChangeEventSourceCoordinator.java:98)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Common Language Runtime(CLR) is not enabled on this instance.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:615)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:537)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7730)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3786)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:456)
        at io.debezium.jdbc.JdbcConnection.prepareQueryAndMap(JdbcConnection.java:735)
        at io.debezium.connector.sqlserver.SqlServerConnection.incrementLsn(SqlServerConnection.java:352)
        at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.executeIteration(SqlServerStreamingChangeEventSource.java:190)
        ... 8 more
```

--> https://dba.stackexchange.com/a/307209

**Comment by vdesabou** [comment]
https://hub.docker.com/u/arm64v8/

**Comment by vdesabou** [comment]
done https://kafka-docker-playground.io/#/how-to-use?id=%f0%9f%a7%91%f0%9f%92%bb-m1-chip-arm64-mac-support
