### ISSUE TITLE
Couchbase source connector test broken since upgrading to 3.4.8

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#38]
```
[2020-07-08 12:17:38,043] ERROR WorkerSourceTask{id=couchbase-source-1} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Couldn't create filter in CouchbaseSourceTask due to an error
	at com.couchbase.connect.kafka.CouchbaseSourceTask.createFilter(CouchbaseSourceTask.java:150)
	at com.couchbase.connect.kafka.CouchbaseSourceTask.start(CouchbaseSourceTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: example.KeyFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:352)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:341)
	at com.couchbase.connect.kafka.CouchbaseSourceTask.createFilter(CouchbaseSourceTask.java:148)
	... 9 more
```

https://travis-ci.com/github/vdesabou/kafka-docker-playground/jobs/358712229

**Comment by vdesabou** [comment]
Seems like there will be more to do once we use 4.x: https://github.com/couchbase/kafka-connect-couchbase/blob/41f26bec4c7afb3b6cf2a1ede1b2009e28c2564c/config/migrate-config-3-to-4.sh
