### ISSUE TITLE
CP 7.5.2: topic produce failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#4571]
```
playground topic produce -t topic-avro-example --nb-messages 3 << 'EOF'
{
  "fields": [
    {
      "doc": "count",
      "name": "count",
      "type": "long"
    },
    {
      "doc": "First Name of Customer",
      "name": "first_name",
      "type": "string"
    },
    {
      "doc": "Last Name of Customer",
      "name": "last_name",
      "type": "string"
    },
    {
      "doc": "Address of Customer",
      "name": "address",
      "type": "string"
    },
    {
      "name": "createdDate",
      "type": {
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    },
    {
      "default": null,
      "name": "myDecimal",
      "type": [
        "null",
        {
          "logicalType": "decimal",
          "precision": 15,
          "scale": 2,
          "type": "bytes"
        }
      ]
    },
    {
      "default": null,
      "name": "warranty_expiration",
      "type": [
        "null",
        {
          "logicalType": "date",
          "type": "int"
        }
      ]
    }
  ],
  "name": "Customer",
  "namespace": "com.github.vdesabou",
  "type": "record"
}
EOF

```

```
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
        at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:174)
        at io.confluent.kafka.formatter.AvroMessageReader$AvroMessageSerializer.serialize(AvroMessageReader.java:167)
        at io.confluent.kafka.formatter.SchemaMessageReader.readMessage(SchemaMessageReader.java:406)
        at kafka.tools.ConsoleProducer$$anon$1$$anon$2.hasNext(ConsoleProducer.scala:67)
        at kafka.tools.ConsoleProducer$.loopReader(ConsoleProducer.scala:90)
        at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:99)
        at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
Caused by: java.lang.ClassCastException: value 2329377083941.20 (a java.math.BigDecimal) cannot be cast to expected type bytes at AccountStatement.amount
        at org.apache.avro.path.TracingClassCastException.summarize(TracingClassCastException.java:79)
        at org.apache.avro.path.TracingClassCastException.summarize(TracingClassCastException.java:30)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:84)
        at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.writeDatum(AbstractKafkaAvroSerializer.java:192)
        at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:162)
        ... 6 more
Caused by: java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.nio.ByteBuffer (java.math.BigDecimal and java.nio.ByteBuffer are in module java.base of loader 'bootstrap')
        at org.apache.avro.generic.GenericDatumWriter.writeBytes(GenericDatumWriter.java:400)
        at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:168)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:93)
        at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:245)
        at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:234)
        at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:145)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:95)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
        ... 8 more

```

**Comment by vdesabou** [comment]
```
Regression: logical types not working for specific Avro types

This affects 7.4.3 and 7.5.2, and will be fixed in 7.4.4 and 7.5.3
```
