### ISSUE TITLE
java.lang.IllegalStateException: Invalid telemetry state transition from TERMINATING_PUSH_IN_PROGRESS to PUSH_NEEDED; the valid telemetry state transitions from TERMINATING_PUSH_IN_PROGRESS are: TERMINATED

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#5942]
```
playground topic consume --topic topic-json
10:17:43 ℹ️ ✨ Display content of topic topic-json, it contains 5 messages
10:17:43 ℹ️ 🔮🙅 topic is not using any schema for key
10:17:43 ℹ️ 🔮🙅 topic is not using any schema for value
CreateTime:2024-09-30 10:14:35.262|Partition:0|Offset:0|Headers:NO_HEADERS|Key:null|Value:{"nested":{"phone":"96-287795-302534-0","website":"delirious-nickname.name"},"id":1,"name":"Donny.Shields","email":"Jamal60@example.com","phone":"54-128410-634271-6","website":"silent-toreador.net","city":"Swiftworth","company":"Gerlach, Schultz and Runte"}|ValueSchemaId:
CreateTime:2024-09-30 10:14:35.341|Partition:0|Offset:1|Headers:NO_HEADERS|Key:null|Value:{"nested":{"phone":"89-449958-002506-5","website":"upset-pathology.org"},"id":2,"name":"Amos.Prohaska7","email":"Cortney_Fisher84@example.net","phone":"84-017506-440124-7","website":"frizzy-hamburger.net","city":"South Mark","company":"O'Connell and Sons"}|ValueSchemaId:
CreateTime:2024-09-30 10:14:35.342|Partition:0|Offset:2|Headers:NO_HEADERS|Key:null|Value:{"nested":{"phone":"50-140837-291466-2","website":"webbed-hood.info"},"id":3,"name":"Sally.Ferry","email":"Alyson.Bergnaum@example.org","phone":"89-938117-017303-1","website":"bright-consignment.name","city":"Kuhlmanport","company":"Pfeffer - Murazik"}|ValueSchemaId:
CreateTime:2024-09-30 10:14:35.342|Partition:0|Offset:3|Headers:NO_HEADERS|Key:null|Value:{"nested":{"phone":"88-191799-908950-0","website":"lovely-facility.info"},"id":4,"name":"Krystina_Crona85","email":"Seth.Hills53@example.com","phone":"59-454755-060323-9","website":"blank-tender.com","city":"Lake Theresebury","company":"Bartoletti - Jakubowski"}|ValueSchemaId:
CreateTime:2024-09-30 10:14:35.342|Partition:0|Offset:4|Headers:NO_HEADERS|Key:null|Value:{"nested":{"phone":"78-779907-602166-2","website":"sociable-crumb.name"},"id":5,"name":"Joanny_Bartell-Steuber","email":"Perry_Effertz41@example.net","phone":"53-189985-108877-6","website":"forceful-bouquet.org","city":"North Paulaport","company":"Bailey - Hickle"}|ValueSchemaId:
[2024-09-30 08:17:46,916] WARN Error updating client telemetry state, disabled telemetry (org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter)
java.lang.IllegalStateException: Invalid telemetry state transition from TERMINATING_PUSH_IN_PROGRESS to PUSH_NEEDED; the valid telemetry state transitions from TERMINATING_PUSH_IN_PROGRESS are: TERMINATED
at org.apache.kafka.common.telemetry.ClientTelemetryState.validateTransition(ClientTelemetryState.java:163)
at org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter$DefaultClientTelemetrySender.maybeSetState(ClientTelemetryReporter.java:814)
at org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter$DefaultClientTelemetrySender.handleResponse(ClientTelemetryReporter.java:518)
at org.apache.kafka.clients.NetworkClient$TelemetrySender.handleResponse(NetworkClient.java:1449)
at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:1055)
at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:679)
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:281)
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:243)
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitPendingRequests(ConsumerNetworkClient.java:354)
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:1139)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:988)
at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.lambda$close$3(LegacyKafkaConsumer.java:1136)
at org.apache.kafka.common.utils.Utils.swallow(Utils.java:1233)
at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.close(LegacyKafkaConsumer.java:1136)
at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.close(LegacyKafkaConsumer.java:1105)
at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.close(LegacyKafkaConsumer.java:1093)
at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1757)
at kafka.tools.ConsoleConsumer$ConsumerWrapper.cleanup(ConsoleConsumer.scala:488)
at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:79)
at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:54)
at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
[2024-09-30 08:17:46,918] WARN Unable to transition state after successful push telemetry from state TERMINATING_PUSH_IN_PROGRESS (org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter)

```

**Comment by vdesabou** [comment]
```
[2024-10-02 12:14:13,098] WARN [s3-sink2|task-0] Error updating client telemetry state, disabled telemetry (org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter:822)
java.lang.IllegalStateException: Invalid telemetry state transition from TERMINATING_PUSH_IN_PROGRESS to PUSH_NEEDED; the valid telemetry state transitions from TERMINATING_PUSH_IN_PROGRESS are: TERMINATED
        at org.apache.kafka.common.telemetry.ClientTelemetryState.validateTransition(ClientTelemetryState.java:163)
        at org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter$DefaultClientTelemetrySender.maybeSetState(ClientTelemetryReporter.java:814)
        at org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter$DefaultClientTelemetrySender.handleResponse(ClientTelemetryReporter.java:518)
        at org.apache.kafka.clients.NetworkClient$TelemetrySender.handleResponse(NetworkClient.java:1449)
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:1055)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:679)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:281)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:243)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitPendingRequests(ConsumerNetworkClient.java:354)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:1139)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:988)
        at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.lambda$close$3(LegacyKafkaConsumer.java:1136)
        at org.apache.kafka.common.utils.Utils.swallow(Utils.java:1233)
        at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.close(LegacyKafkaConsumer.java:1136)
        at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.close(LegacyKafkaConsumer.java:1105)
        at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.close(LegacyKafkaConsumer.java:1093)
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1757)
        at org.apache.kafka.common.utils.Utils.closeQuietly(Utils.java:1308)
        at org.apache.kafka.common.utils.Utils.closeQuietly(Utils.java:1291)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:208)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:241)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:284)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$7(Plugins.java:339)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-02 12:14:13,098] WARN [s3-sink2|task-0] Unable to transition state after successful push telemetry from state TERMINATING_PUSH_IN_PROGRESS (org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter:519)
```
