### ISSUE TITLE
Replicator with connect: error with 5.4.0 NoClassDefFoundError: io/confluent/connect/replicator/util/RegexValidator

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#8]
Getting:

```
[2020-01-23 14:29:30,125] WARN /connectors/replicate-europe-to-us/config (org.eclipse.jetty.server.HttpChannel)
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/replicator/util/RegexValidator
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/replicator/util/RegexValidator
	at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:254)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:236)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:436)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	... 28 more
Caused by: java.lang.NoClassDefFoundError: io/confluent/connect/replicator/util/RegexValidator
	at io.confluent.connect.replicator.ReplicatorSourceConnectorConfig.baseConfigDef(ReplicatorSourceConnectorConfig.java:156)
	at io.confluent.connect.replicator.ReplicatorSourceConnectorConfig.<clinit>(ReplicatorSourceConnectorConfig.java:123)
	at io.confluent.connect.replicator.ReplicatorSourceConnector.config(ReplicatorSourceConnector.java:161)
	at org.apache.kafka.connect.connector.Connector.validate(Connector.java:129)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:313)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:745)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:742)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:342)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.ClassNotFoundException: io.confluent.connect.replicator.util.RegexValidator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by vdesabou** [comment]
The class is contained in kafka-connect-replicator/replicator-common-5.4.0.jar

```  
 148 Sat Jan 11 03:45:58 UTC 2020 META-INF/MANIFEST.MF
     0 Sat Jan 11 03:45:58 UTC 2020 META-INF/
     0 Sat Jan 11 03:45:58 UTC 2020 io/
     0 Sat Jan 11 03:45:58 UTC 2020 io/confluent/
     0 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/
     0 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/
     0 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/
     0 Sat Jan 11 03:45:58 UTC 2020 META-INF/maven/
     0 Sat Jan 11 03:45:58 UTC 2020 META-INF/maven/io.confluent/
     0 Sat Jan 11 03:45:58 UTC 2020 META-INF/maven/io.confluent/replicator-common/
 16666 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/NewReplicatorAdminClient.class
  3407 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/ReplicatorAdminClientWithZk$1.class
   654 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/TopicMetadata.class
  1338 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/NewReplicatorAdminClient$1.class
  4415 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/Utils.class
   340 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/ReplicatorAdminClient$TopicMetadataListener.class
 13033 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/ReplicatorAdminClientWithZk.class
  1342 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/RegexValidator.class
  1248 Sat Jan 11 03:45:44 UTC 2020 META-INF/maven/io.confluent/replicator-common/pom.xml
  1585 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/ReplicatorAdminClient.class
    95 Sat Jan 11 03:45:58 UTC 2020 META-INF/maven/io.confluent/replicator-common/pom.properties
  4812 Sat Jan 11 03:45:58 UTC 2020 io/confluent/connect/replicator/util/NewReplicatorAdminClient$TopicMetadataTask.class
```

No sure why it is not working when specifying `plugin.path=/usr/share/java/kafka-connect-replicator`

Anyway, setting `plugin.path=/usr/share/java`fixed the problem

**Comment by vdesabou** [comment]
Also contained in:

timestamp-interceptor-5.4.0.jar

```
  1342 Sat Jan 11 03:46:00 UTC 2020 io/confluent/connect/replicator/util/RegexValidator.class
```

**Comment by vdesabou** [comment]
in 5.3.2, Looks like it is only an inner class,  contained in kafka-connect-replicator-5.3.2.jar

```
  1507 Fri Dec 13 18:11:02 UTC 2019 io/confluent/connect/replicator/ReplicatorSourceConnectorConfig$RegexValidator.class
```

**Comment by vdesabou** [comment]
> the Connect plugin loader expects plugins to be in subdirectories below the plugin.path. For instance replicator jars should be <plugin.path>/kafka-connect-replicator/some.jar

> if you point connect directly at the replicator directory it will expect to find subdirectories with plugins in it
