### ISSUE TITLE
Using CLASSPATH for setting replicator-rest-extension jar does not work with UBI8 image

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#80]
This [commit](https://github.com/vdesabou/kafka-docker-playground/commit/028189afeadaa2026c1efb012b7d36e69a43f54a) breaks tests with UBI8

**Comment by vdesabou** [comment]
```
[2020-09-16 08:52:13,273] ERROR Failed to start Connect (org.apache.kafka.connect.cli.ConnectDistributed)
org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements interface org.apache.kafka.connect.rest.ConnectRestExtension and which name matches io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:436)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugins(Plugins.java:422)
	at org.apache.kafka.connect.runtime.rest.RestServer.registerRestExtensions(RestServer.java:446)
	at org.apache.kafka.connect.runtime.rest.RestServer.initializeResources(RestServer.java:238)
	at org.apache.kafka.connect.runtime.Connect.start(Connect.java:55)
	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:130)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:78)
```
