### ISSUE TITLE
connect-salesforce-sobject-sink is broken

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#82]
```
[2020-09-18 15:58:57,389] ERROR Retry timeout reached. No more retries. (io.confluent.salesforce.sobject.SalesforceSObjectSinkTask)
[2020-09-18 15:58:57,391] ERROR WorkerSinkTask{id=salesforce-sobject-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Exception encountered while calling salesforce (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.ConnectException: Exception encountered while calling salesforce
        at io.confluent.salesforce.rest.SalesforceRestClientImpl.postAndParse(SalesforceRestClientImpl.java:256)
        at io.confluent.salesforce.rest.SalesforceRestClientImpl.updateSObject(SalesforceRestClientImpl.java:415)
        at io.confluent.salesforce.sobject.SalesforceSObjectSinkTask.putRecord(SalesforceSObjectSinkTask.java:111)
        at io.confluent.salesforce.sobject.SalesforceSObjectSinkTask.lambda$put$0(SalesforceSObjectSinkTask.java:59)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.confluent.salesforce.sobject.SalesforceSObjectSinkTask.put(SalesforceSObjectSinkTask.java:57)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
[{"message":"invalid cross reference id","errorCode":"INVALID_CROSS_REFERENCE_KEY","fields":[]}]
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1097)
        at io.confluent.salesforce.rest.SalesforceRestClientImpl.executeAndParse(SalesforceRestClientImpl.java:233)
        at io.confluent.salesforce.rest.SalesforceRestClientImpl.postAndParse(SalesforceRestClientImpl.java:254)
        ... 16 more
```

**Comment by vdesabou** [comment]
Need to do that ? https://github.com/vdesabou/kafka-docker-playground/commit/73fb00339b19d1079cb19ffd5d125e92e4e779ac
