### ISSUE TITLE
HBase sink connector test is silently failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#874]
https://github.com/vdesabou/kafka-docker-playground/runs/2249612975#step:6:15847

**Comment by vdesabou** [comment]
The issue seems to boil down to this exception in connect logs

```
Caused by: java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.putLong(java.lang.Object, int, long)'
at org.apache.hadoop.hbase.util.UnsafeAccess.putLong(UnsafeAccess.java:248)
at org.apache.hadoop.hbase.util.Bytes$ConverterHolder$UnsafeConverter.putLong(Bytes.java:1489)
at org.apache.hadoop.hbase.util.Bytes.putLong(Bytes.java:788)
```

It seems to be due to incompatibility of the JDK `Unsafe` methods between jdk8 vs jdk11. Hbase seems to explicitly not yet have full support for jdk11 - https://hbase.apache.org/book.html#java
