### ISSUE TITLE
HBase sink not working with JDK 11

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#907]
It seems to be due to incompatibility of the JDK Unsafe methods between jdk8 vs jdk11. Hbase seems to explicitly not yet have full support for jdk11 - https://hbase.apache.org/book.html#java

```
2021-04-21T10:52:01.5782257Z [2021-04-21 10:51:56,985] ERROR WorkerSinkTask{id=hbase-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
2021-04-21T10:52:01.5808803Z org.apache.kafka.connect.errors.ConnectException: Error establishing connection from configs:
2021-04-21T10:52:01.5813029Z 	at io.confluent.connect.hbase.client.HBaseConnectionProvider.checkAndReturnConnection(HBaseConnectionProvider.java:87)
2021-04-21T10:52:01.5817193Z 	at io.confluent.connect.hbase.client.HBaseConnectionProvider.newConnection(HBaseConnectionProvider.java:73)
2021-04-21T10:52:01.5823216Z 	at io.confluent.connect.hbase.client.HBaseConnectionProvider.newConnection(HBaseConnectionProvider.java:24)
2021-04-21T10:52:01.5829602Z 	at io.confluent.connect.bigtable.BaseBigtableSinkTask.setupConnection(BaseBigtableSinkTask.java:147)
2021-04-21T10:52:01.5836708Z 	at io.confluent.connect.bigtable.BaseBigtableSinkTask.start(BaseBigtableSinkTask.java:52)
2021-04-21T10:52:01.5841823Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:308)
2021-04-21T10:52:01.5844663Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
2021-04-21T10:52:01.5846952Z 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
2021-04-21T10:52:01.5850747Z 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
2021-04-21T10:52:01.5865908Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-04-21T10:52:01.5868146Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-04-21T10:52:01.5870134Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-21T10:52:01.5872319Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-21T10:52:01.5946555Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-21T10:52:01.5948056Z Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
2021-04-21T10:52:01.5950476Z 	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
2021-04-21T10:52:01.5953341Z 	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
2021-04-21T10:52:01.5956077Z 	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
2021-04-21T10:52:01.5958826Z 	at org.apache.hadoop.hbase.client.HBaseAdmin.checkHBaseAvailable(HBaseAdmin.java:3276)
2021-04-21T10:52:01.5963412Z 	at io.confluent.connect.hbase.client.HBaseConnectionProvider.checkAndReturnConnection(HBaseConnectionProvider.java:84)
2021-04-21T10:52:01.5965770Z 	... 13 more
2021-04-21T10:52:01.5966968Z Caused by: java.lang.reflect.InvocationTargetException
2021-04-21T10:52:01.5994572Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-04-21T10:52:01.5997363Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-04-21T10:52:01.6000528Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-04-21T10:52:01.6003107Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2021-04-21T10:52:01.6008104Z 	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
2021-04-21T10:52:01.6010548Z 	... 17 more
2021-04-21T10:52:01.6012462Z Caused by: java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.putLong(java.lang.Object, int, long)'
2021-04-21T10:52:01.6014863Z 	at org.apache.hadoop.hbase.util.UnsafeAccess.putLong(UnsafeAccess.java:248)
2021-04-21T10:52:01.6016678Z 	at org.apache.hadoop.hbase.util.Bytes$ConverterHolder$UnsafeConverter.putLong(Bytes.java:1489)
2021-04-21T10:52:01.6018935Z 	at org.apache.hadoop.hbase.util.Bytes.putLong(Bytes.java:788)
2021-04-21T10:52:01.6021481Z 	at org.apache.hadoop.hbase.client.ClientIdGenerator.generateClientId(ClientIdGenerator.java:51)
2021-04-21T10:52:01.6025011Z 	at org.apache.hadoop.hbase.client.PerClientRandomNonceGenerator.<init>(PerClientRandomNonceGenerator.java:37)
2021-04-21T10:52:01.6029029Z 	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:689)
2021-04-21T10:52:01.6031872Z 	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:649)
2021-04-21T10:52:01.6033465Z 	... 22 more
2021-04-21T10:52:01.6034926Z [2021-04-21 10:51:56,988] INFO Stopping Task. (io.confluent.connect.bigtable.BaseBigtableSinkTask)
2021-04-21T10:52:01.6036871Z [2021-04-21 10:51:56,990] WARN Could not stop task (org.apache.kafka.connect.runtime.WorkerSinkTask)
2021-04-21T10:52:01.6038211Z java.lang.NullPointerException
2021-04-21T10:52:01.6039798Z 	at io.confluent.connect.bigtable.BaseBigtableSinkTask.stop(BaseBigtableSinkTask.java:117)
2021-04-21T10:52:01.6041900Z 	at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:169)
2021-04-21T10:52:01.6043806Z 	at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:168)
2021-04-21T10:52:01.6045607Z 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:194)
2021-04-21T10:52:01.6173320Z 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
2021-04-21T10:52:01.6176221Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-04-21T10:52:01.6177974Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-04-21T10:52:01.6180537Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-21T10:52:01.6182494Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-21T10:52:01.6183919Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vdesabou** [comment]
This is same issue with GCP BigTable, see https://github.com/vdesabou/kafka-docker-playground/issues/955
