### ISSUE TITLE
Neo4j sink test is silently failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#944]
```
11:20:44 ℹ️ Creating NEO4J Sink connector
Warning: Couldn't read data from file "/tmp/contrib.sink.avro.neo4j.json", 
Warning: this makes an empty POST.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    33  100    33    0     0    160      0 --:--:-- --:--:-- --:--:--   160
{
  "error_code": 500,
  "message": null
}
11:20:49 ℹ️ Verify data is present in Neo4j http://127.0.0.1:7474 (neo4j/connect) by opening http://neo4j:connect@127.0.0.1:7474/ in your browser
Couldn't get a file descriptor referring to the console
```

**Comment by vdesabou** [comment]
```
[2021-05-06 11:42:10,512] ERROR ErrorData(originalTopic=my-topic, timestamp=1620301325193, partition=0, offset=998, exception=org.neo4j.driver.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver. Ensure that you are using driver and server versions that are compatible with one another., key=Name -388094973Surname D, value=Struct{name=Name -388094973,surname=Surname D}, executingClass=class kotlinx.coroutines.BlockingCoroutine) (streams.kafka.connect.sink.Neo4jSinkTask)
org.neo4j.driver.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver. Ensure that you are using driver and server versions that are compatible with one another.
        at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
        at org.neo4j.driver.internal.InternalSession.beginTransaction(InternalSession.java:163)
        at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:147)
        at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:102)
        at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:146)
        at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:124)
        at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:118)
        at streams.kafka.connect.sink.Neo4jService$write$1$1.invoke(Neo4jService.kt:118)
        at streams.kafka.connect.sink.Neo4jService$write$1$1.invoke(Neo4jService.kt:36)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:7)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.kafka.connect.sink.Neo4jService$write$1.invokeSuspend(Neo4jService.kt:116)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at streams.kafka.connect.sink.Neo4jService.write(Neo4jService.kt:115)
        at streams.service.StreamsSinkService.writeWithCypherTemplate(StreamsSinkService.kt:37)
        at streams.service.StreamsSinkService.writeForTopic(StreamsSinkService.kt:43)
        at streams.kafka.connect.sink.Neo4jService$writeDataAsync$2$invokeSuspend$$inlined$flatMap$lambda$1.invokeSuspend(Neo4jService.kt:182)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
        Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
                at org.neo4j.driver.internal.async.connection.HandshakeHandler.protocolNoSupportedByServerError(HandshakeHandler.java:164)
                at org.neo4j.driver.internal.async.connection.HandshakeHandler.handleUnknownSuggestedProtocolVersion(HandshakeHandler.java:145)
                at org.neo4j.driver.internal.async.connection.HandshakeHandler.decode(HandshakeHandler.java:118)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:829)
[2021-05-06 11:42:10,512] ERROR ErrorData(originalTopic=my-topic, timestamp=1620301325194, partition=0, offset=999, exception=org.neo4j.driver.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver. Ensure that you are using driver and server versions that are compatible with one another., key= Name -1838182650Surname B, value=Struct{name=Name -1838182650,surname=Surname B}, executingClass=class kotlinx.coroutines.BlockingCoroutine) (streams.kafka.connect.sink.Neo4jSinkTask)
org.neo4j.driver.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver. Ensure that you are using driver and server versions that are compatible with one another.
        at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
        at org.neo4j.driver.internal.InternalSession.beginTransaction(InternalSession.java:163)
        at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:147)
        at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:102)
        at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:146)
        at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:124)
        at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:118)
        at streams.kafka.connect.sink.Neo4jService$write$1$1.invoke(Neo4jService.kt:118)
        at streams.kafka.connect.sink.Neo4jService$write$1$1.invoke(Neo4jService.kt:36)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:7)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:12)
        at streams.kafka.connect.sink.Neo4jService$write$1.invokeSuspend(Neo4jService.kt:116)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at streams.kafka.connect.sink.Neo4jService.write(Neo4jService.kt:115)
        at streams.service.StreamsSinkService.writeWithCypherTemplate(StreamsSinkService.kt:37)
        at streams.service.StreamsSinkService.writeForTopic(StreamsSinkService.kt:43)
        at streams.kafka.connect.sink.Neo4jService$writeDataAsync$2$invokeSuspend$$inlined$flatMap$lambda$1.invokeSuspend(Neo4jService.kt:182)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
        Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
                at org.neo4j.driver.internal.async.connection.HandshakeHandler.protocolNoSupportedByServerError(HandshakeHandler.java:164)
                at org.neo4j.driver.internal.async.connection.HandshakeHandler.handleUnknownSuggestedProtocolVersion(HandshakeHandler.java:145)
                at org.neo4j.driver.internal.async.connection.HandshakeHandler.decode(HandshakeHandler.java:118)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:829)
```
