### ISSUE TITLE
Add Operator 2.0 example with ccloud

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#972]
https://github.com/confluentinc/operator-earlyaccess/tree/master/ccloud-integration

**Comment by vdesabou** [comment]
```
[ERROR] 2021-05-10 14:00:11,051 [main] io.confluent.ksql.rest.server.KsqlServerMain tryStartApp - Unhandled exception in server startup
io.confluent.ksql.exception.KafkaResponseGetFailedException: Failed to guarantee existence of topic _confluent-ksql-confluent.ksqldb-tls__command_topic
	at io.confluent.ksql.services.KafkaTopicClientImpl.createTopic(KafkaTopicClientImpl.java:140)
	at io.confluent.ksql.services.KafkaTopicClient.createTopic(KafkaTopicClient.java:102)
	at io.confluent.ksql.rest.util.KsqlInternalTopicUtils.ensureTopic(KsqlInternalTopicUtils.java:82)
	at io.confluent.ksql.rest.server.KsqlRestApplication.registerCommandTopic(KsqlRestApplication.java:900)
	at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:428)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:367)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:350)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:91)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:66)
Caused by: org.apache.kafka.common.errors.PolicyViolationException: Topic replication factor must be 3
```

**Comment by vdesabou** [comment]
https://github.com/vdesabou/kafka-docker-playground/tree/master/ccloud/operator-early-access
