### ISSUE TITLE
cloud-demo stream app failing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#99]
```
INFO stream-client [simple-stream-f9fd913e-748e-4f9b-b6a9-4ac506c1a5fe] State transition from REBALANCING to ERROR (org.apache.kafka.streams.KafkaStreams:285) 
ERROR stream-client [simple-stream-f9fd913e-748e-4f9b-b6a9-4ac506c1a5fe] All stream threads have died. The instance will be in error state and should be closed. (org.apache.kafka.streams.KafkaStreams:445) 
INFO stream-thread [simple-stream-f9fd913e-748e-4f9b-b6a9-4ac506c1a5fe-StreamThread-2] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1150) 
Exception in thread "simple-stream-f9fd913e-748e-4f9b-b6a9-4ac506c1a5fe-StreamThread-2" org.apache.kafka.streams.errors.StreamsException: Existing internal topic simple-stream-KSTREAM-REDUCE-STATE-STORE-0000000003-repartition has invalid partitions: expected: 2; actual: 6. Use 'kafka.tools.StreamsResetter' tool to clean up invalid topics before processing.
        at org.apache.kafka.streams.processor.internals.InternalTopicManager.validateTopics(InternalTopicManager.java:237)
        at org.apache.kafka.streams.processor.internals.InternalTopicManager.makeReady(InternalTopicManager.java:105)
        at org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor.prepareTopic(StreamsPartitionAssignor.java:1247)
        at org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor.assign(StreamsPartitionAssignor.java:485)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.performAssignment(ConsumerCoordinator.java:567)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.onJoinLeader(AbstractCoordinator.java:678)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.access$1500(AbstractCoordinator.java:111)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:597)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:574)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1096)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1076)
        at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:204)
        at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:167)
        at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:127)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:599)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:409)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:294)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:212)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:418)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:358)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:490)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1275)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1241)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:853)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:753)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
INFO stream-client [simple-stream-f9fd913e-748e-4f9b-b6a9-4ac506c1a5fe] State transition from ERROR to PENDING_SHUTDOWN (org.apache.kafka.streams.KafkaStreams:285) 
```

**Comment by vdesabou** [comment]
```
kafka-streams-application-reset --application-id simple-stream --bootstrap-servers pkcxxx.confluent.cloud:9092 --config-file ~/.ccloud/config --to-latest
```
